### PR TITLE
feat(update-badge): clarify what is the full update

### LINKED ISSUE #27: Latest update date clarification
~~Updated 48 min ago but navbar shows that the last update took place "4 day ago"~~

need to be more explicit (tooltip + modify the sentence "Dernière mise à jour")

image

### PR DESCRIPTION
**Pull request by FranckG28**
Closes #27 

Image

### CODE REVIEW

**Comment by ErenMustafaGit** [comment]
Maybe keep purple color for real action buttons and put blue color for secondary information --> Then put this badge in blue color ? 

For example, filter by new products will be : 
image

**Comment by FranckG28** [comment]
> Maybe keep purple color for real action buttons and put blue color for secondary information --> Then put this badge in blue color ?
> 
> For example, filter by new products will be : image

Ok for the color ! But i'm not convinced by the badge design for the moment 🤓 We will talk about it in the correct PR

**Comment by FranckG28** [comment]
Screenshot 2023-09-18 at 21 46 37

**Review by ErenMustafaGit — APPROVED** [review]
AMAZIIIIIIIING 😍

**Pull request merged**
